AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: An AWS Serverless Specification template describing your function.
Resources:
  txwgaircraftpositiondata:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: lambda_function.lambda_handler
      Runtime: python3.8
      CodeUri: [S3 location for ZIP file containing lambda_function.py]
      Description: 'OpenSky Network to ArcGIS Online Aircraft Position Data Sync'
      MemorySize: 128
      Timeout: 10
      Role: >-
        [lambdaServiceRole]
      Events:
        Schedule1:
          Type: Schedule
          Properties:
            Schedule: rate(5 minutes)
      Environment:
        Variables:
          arcGisClientId: [ArcGIS Client ID - Not Implemented]
          arcGisClientSecret: [ArcGIS Client Secret - Not Implemented]
          arcGisToken: >-
            [ArcGIS Temporary Access Token for App Owner]
          arcGisUrl: >-
            https://services{x}.arcgis.com/{appID}/arcgis/rest/services/{layerName}/FeatureServer
          openSkyUrl: 'https://opensky-network.org/api/states/all'
      Layers:
        - 'arn:aws:lambda:us-east-1:716881127175:layer:requests:2'
